### ISSUE TITLE
color demo

### ISSUE THREAD

**Issue by koendv** [RobTillaart/ANSI#7]
Rob,

OK als ik je ansi color demo hier gebruik?
https://github.com/koendv/Arduino-RTTStream/blob/main/examples/Color/Color.ino

dank,
koen

**Comment by RobTillaart** [comment]
Hoi Koen, 
Je bent een van de weinigen die het vraagt en alleen daarom al zou je het mogen :)
Licentie is MIT, dus je kan het vrij gebruiken onder voorwaarde van bron vermelding + licentie .

![image](https://user-images.githubusercontent.com/462844/141522182-f2ef71f6-73bf-4490-b5dd-3b60d8c10ef7.png)

Je moet het dus wel zelf wel goed testen!

Wat gaat het precies worden? Of is dat nog geheim? Kan ook.

**Comment by koendv** [comment]
OK, dank.
Dit is om wat kleur te brengen in "printf-debugging". Wat ik gedaan heb is een commercieel debug product er laten uitzien als een Arduino seriele poort.

Ik heb een "blue pill" bordje met een arm processor die een arduino sketch draait.
Dat bordje met arduino hangt aan een debugger probe merk "Segger JLink".
Op de pc kan je dan een sketch downloaden, variabelen bekijken, single-steppen - het gewone.

Wat mijn bibliotheek eraan toevoegt is het volgende: als je in je sketch naar een speciale Stream schrijft, komt de output op de pc terecht. Vlug (een 200.000 karakters/s op usb2.0) en zonder dat je usb of fysische seriele poorten aanraakt. Alles gaat over de debug interface. Ideaal voor "printf-debugging". Met de ansi bibliotheek kan ik daar wat kleur in brengen - een belangrijke lijn in het rood bevoorbeeld.

Nadeel dat het enkel op arm processors werkt, en dat het een commercieel product nodig heeft.

koen

**Comment by RobTillaart** [comment]
Leuk project, soort syntax highlighting voor debug info!

Zijn er geen specificaties van dat Segger Jlink protocol?  
Kan me voorstellen dat daar wat open source van bestaat

**Comment by koendv** [comment]
OK. Er zijn twee mogelijkheden. 
- je koopt bij https://www.ak-modul-bus.de/ een "Segger J-Link EDU" of "Segger J-Link Mini EDU". Die EDU is voor studenten en OSS. De prijzen zijn redelijk, maar er is geen commercieel gebruik toegelaten.
- je gebruikt goedkope "Chinese" debugger hardware en OpenOCD open source debug software. Het feature dat ik gebruik is hier beschreven: https://openocd.org/doc/html/General-Commands.html#Real-Time-Transfer-_0028RTT_0029 Dit feature is tamelijk "vers".

Als het de eerste keer is, zou ik het mezelf eenvoudig maken en een J-Link EDU kopen.

Het volledige setup ziet er dan zo uit:
- blue pill stm32f103c8t6 128kbyte flash
- jlink edu of jlink edu mini
- Arduino IDE met stm32duino board package https://github.com/stm32duino/BoardManagerFiles
- RTTStream library

koen

**Comment by RobTillaart** [comment]
OK, thanks for the links.
